CREATE TABLE USUARIOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    DATA_NASCIMENTO TIMESTAMP,
    EMAIL VARCHAR(100),
    SENHA VARCHAR(100)
);

CREATE TABLE ENDERECO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CEP VARCHAR(10),
    ESTADO VARCHAR(50),
    CIDADE VARCHAR(50),
    BAIRRO VARCHAR(50),
    ENDERECO VARCHAR(100),
    NUM_CASA INT,
    USUARIO_ID BIGINT,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);
