name: Testes com cobertura Jacoco

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Rodar testes e gerar cobertura
        run: mvn clean verify

      - name: Publicar relatório Jacoco
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-relatorio
          path: target/site/jacoco
